import {GAME_CONSTANTS, GAME_SPRITES} from "../../model/game/storage/gameConstants.js";

export function initSprites() {
    GAME_SPRITES.ENEMY.g.src = GAME_CONSTANTS.ENEMY_PATH.g;
    GAME_SPRITES.ENEMY.r.src = GAME_CONSTANTS.ENEMY_PATH.r;
    GAME_SPRITES.ENEMY.s.src = GAME_CONSTANTS.ENEMY_PATH.s;
    GAME_SPRITES.ENEMY.bg.img.src = GAME_CONSTANTS.ENEMY_PATH.bg;
    GAME_SPRITES.ENEMY.br.img.src = GAME_CONSTANTS.ENEMY_PATH.br;
    GAME_SPRITES.ENEMY.bs.img.src = GAME_CONSTANTS.ENEMY_PATH.bs;

    GAME_SPRITES.PLAYER.g.src = GAME_CONSTANTS.PLAYER_PATH.g;
    GAME_SPRITES.PLAYER.r.src = GAME_CONSTANTS.PLAYER_PATH.r;
    GAME_SPRITES.PLAYER.s.src = GAME_CONSTANTS.PLAYER_PATH.s;
    GAME_SPRITES.PLAYER.bg.img.src = GAME_CONSTANTS.PLAYER_PATH.bg;
    GAME_SPRITES.PLAYER.br.img.src = GAME_CONSTANTS.PLAYER_PATH.br;
    GAME_SPRITES.PLAYER.bs.img.src = GAME_CONSTANTS.PLAYER_PATH.bs;

    GAME_SPRITES.HEALTH_BAR.src = GAME_CONSTANTS.HEALTH_BAR_PATH;

    GAME_SPRITES.EFFECTS.MUZZLE_FLASH.img.src = GAME_CONSTANTS.MUZZLE_FLASH_PATH;
    GAME_SPRITES.EFFECTS.EXPLOSION.img.src = GAME_CONSTANTS.EXPLOSION_PATH;
    GAME_SPRITES.EFFECTS.PLAYER_DEATH.img.src = GAME_CONSTANTS.PLAYER_DEATH_PATH;
    GAME_SPRITES.EFFECTS.PLAYER_HIT.img.src = GAME_CONSTANTS.PLAYER_HIT_PATH;
    GAME_SPRITES.EFFECTS.EXPLOSION_S.img.src = GAME_CONSTANTS.EXPLOSION_S_PATH;
    GAME_SPRITES.EFFECTS.SHIELD.img.src = GAME_CONSTANTS.SHIELD_PATH;
    GAME_SPRITES.EFFECTS.MUZZLE_FLASH_S.img.src = GAME_CONSTANTS.MUZZLE_FLASH_S_PATH;
}