import {GAME_CONSTANTS, GAME_SPRITES} from "../../model/game/storage/gameConstants.js";

export function initSprites() {
    GAME_SPRITES.PLAYER_GOES.src = GAME_CONSTANTS.PLAYER_SKIN_BLUE_PATH;
    GAME_SPRITES.BULLET_FLIES.src = GAME_CONSTANTS.BULLET_SKIN_PATH;

    GAME_SPRITES.ENEMY_GOES.src = GAME_CONSTANTS.ENEMY_SPRITE_LIST_PATH;
    GAME_SPRITES.ENEMY_BULLET_FLIES.src = GAME_CONSTANTS.ENEMY_BULLET_SKIN_PATH;

    GAME_SPRITES.HEALTH_BAR.src = GAME_CONSTANTS.HEALTH_BAR_PATH;
}