export const GAME_CONSTANTS = {
    PLAYER_SPEED: 0.2,
    BULLET_SPEED: 1.5,
    CANVAS_START: 0,

    PLAYER_VISUAL_SIZE: 20,
    PLAYER_START_X: 650,
    PLAYER_START_Y: 400,

    BULLET_WIDTH: 10,
    BULLET_HEIGHT: 50,
    BULLET_COLOR: "#cdcbcb"
}