import {GAME_CONSTANTS, GAME_SPRITES} from "../model/storage/gameConstants.js";

export function initSprites() {
    GAME_SPRITES.PLAYER_GOES.src = GAME_CONSTANTS.PLAYER_SKIN_BLUE;
    GAME_SPRITES.BULLET_FLIES.src = GAME_CONSTANTS.BULLET_SKIN;

    GAME_SPRITES.ENEMY_GOES.src = GAME_CONSTANTS.ENEMY_SKIN;
    GAME_SPRITES.ENEMY_BULLET_FLIES.src = GAME_CONSTANTS.ENEMY_BULLET_SKIN;
}